
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const PROCESS_IMAGE_SUCCESS = " PROCESS_IMAGE_SUCCESS";
export const PROCESS_IMAGE_FAILURE = "PROCESS_IMAGE_FAILURE";




